default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: erty9510asd
  pool: 5

development:
  <<: *default
  database: railsjobhub_development


test:
  <<: *default
  database: railsjobhub_test
